name: lectureslider
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.6.20
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - intel-openmp=2020.1
  - jpeg=9b
  - libopencv=4.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - numpy=1.18.5
  - numpy-base=1.18.5
  - opencv=4.0.1
  - openssl=1.1.1g
  - pip=20.1.1
  - py-opencv=4.0.1
  - python=3.8.3
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - chardet==3.0.4
    - pysrt==1.1.2

